# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Big If
email: wudixiaotie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Most of the time, I feel like I'm an idiot. The worse is I don't know why!! :(
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wudixiaotie.github.io" # the base hostname & protocol for your site
twitter_username: wudixiaotie
github_username:  wudixiaotie

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 2
paginate_path: "page:num"